---
Name: 'SEO_FacebookDomainInsights'
Before:
  - '#SEO_Metadata'
---
SiteConfig:
  extensions:
    - 'SEO_FacebookDomainInsights_SiteConfig_DataExtension'

SiteTree:
  extensions:
    - 'SEO_FacebookDomainInsights_SiteTree_DataExtension'

Member:
  extensions:
    - 'SEO_FacebookDomainInsights_Member_DataExtension'
