---
Name: 'SEO_FacebookInsights'
Before:
  - '#SEO_Metadata'
  - '#SEO_Icons'
  - '#SEO_Authorship'
---
SiteConfig:
  extensions:
    - 'SEO_FacebookInsights_SiteConfig_DataExtension'

SiteTree:
  extensions:
    - 'SEO_FacebookInsights_SiteTree_DataExtension'

Member:
  extensions:
    - 'SEO_FacebookInsights_Member_DataExtension'
